/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "ADCHandler.v:1" *)
module ADCHandler(enable, reset, clk, analog_ramp, ADC_finished, out);
  (* src = "ADCHandler.v:13" *)
  wire _000_;
  (* src = "ADCHandler.v:13" *)
  wire [7:0] _001_;
  (* src = "ADCHandler.v:13" *)
  wire [7:0] _002_;
  (* src = "ADCHandler.v:34" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  (* src = "ADCHandler.v:13" *)
  wire _040_;
  (* src = "ADCHandler.v:13" *)
  wire _041_;
  (* src = "ADCHandler.v:13" *)
  wire _042_;
  (* src = "ADCHandler.v:13" *)
  wire _043_;
  (* src = "ADCHandler.v:13" *)
  wire _044_;
  (* src = "ADCHandler.v:13" *)
  wire _045_;
  (* src = "ADCHandler.v:13" *)
  wire _046_;
  (* src = "ADCHandler.v:13" *)
  wire _047_;
  (* src = "ADCHandler.v:13" *)
  wire _048_;
  (* src = "ADCHandler.v:13" *)
  wire _049_;
  (* src = "ADCHandler.v:13" *)
  wire _050_;
  (* src = "ADCHandler.v:13" *)
  wire _051_;
  (* src = "ADCHandler.v:13" *)
  wire _052_;
  (* src = "ADCHandler.v:13" *)
  wire _053_;
  (* src = "ADCHandler.v:13" *)
  wire _054_;
  (* src = "ADCHandler.v:13" *)
  wire _055_;
  (* src = "ADCHandler.v:13" *)
  wire _056_;
  (* src = "ADCHandler.v:34" *)
  wire _057_;
  (* src = "ADCHandler.v:7" *)
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  (* src = "ADCHandler.v:5" *)
  wire _067_;
  (* src = "ADCHandler.v:11" *)
  wire _068_;
  (* src = "ADCHandler.v:11" *)
  wire _069_;
  (* src = "ADCHandler.v:11" *)
  wire _070_;
  (* src = "ADCHandler.v:11" *)
  wire _071_;
  (* src = "ADCHandler.v:11" *)
  wire _072_;
  (* src = "ADCHandler.v:11" *)
  wire _073_;
  (* src = "ADCHandler.v:11" *)
  wire _074_;
  (* src = "ADCHandler.v:11" *)
  wire _075_;
  (* src = "ADCHandler.v:3" *)
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  (* src = "ADCHandler.v:9" *)
  wire _133_;
  (* src = "ADCHandler.v:9" *)
  wire _134_;
  (* src = "ADCHandler.v:9" *)
  wire _135_;
  (* src = "ADCHandler.v:9" *)
  wire _136_;
  (* src = "ADCHandler.v:9" *)
  wire _137_;
  (* src = "ADCHandler.v:9" *)
  wire _138_;
  (* src = "ADCHandler.v:9" *)
  wire _139_;
  (* src = "ADCHandler.v:9" *)
  wire _140_;
  (* src = "ADCHandler.v:4" *)
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "ADCHandler.v:8" *)
  output ADC_finished;
  (* src = "ADCHandler.v:7" *)
  output analog_ramp;
  (* src = "ADCHandler.v:5" *)
  input clk;
  (* init = 8'h00 *)
  (* src = "ADCHandler.v:11" *)
  wire [7:0] digital_ramp;
  (* src = "ADCHandler.v:3" *)
  input enable;
  (* src = "ADCHandler.v:9" *)
  output [7:0] out;
  (* src = "ADCHandler.v:4" *)
  input reset;
  IVX1_CV _168_ (
    .A(_067_),
    .Y(_066_)
  );
  IVX1_CV _169_ (
    .A(_141_),
    .Y(_090_)
  );
  ANX1_CV _170_ (
    .A(_069_),
    .B(_068_),
    .Y(_091_)
  );
  ANX1_CV _171_ (
    .A(_071_),
    .B(_070_),
    .Y(_092_)
  );
  ANX1_CV _172_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  ANX1_CV _173_ (
    .A(_072_),
    .B(_093_),
    .Y(_094_)
  );
  ANX1_CV _174_ (
    .A(_073_),
    .B(_094_),
    .Y(_095_)
  );
  ANX1_CV _175_ (
    .A(_074_),
    .B(_095_),
    .Y(_096_)
  );
  NDX1_CV _176_ (
    .A(_075_),
    .B(_096_),
    .Y(_097_)
  );
  ANX1_CV _177_ (
    .A(_076_),
    .B(_097_),
    .Y(_098_)
  );
  NDX1_CV _178_ (
    .A(_076_),
    .B(_097_),
    .Y(_099_)
  );
  NDX1_CV _179_ (
    .A(_058_),
    .B(_099_),
    .Y(_100_)
  );
  NDX1_CV _180_ (
    .A(_067_),
    .B(_098_),
    .Y(_101_)
  );
  NDX1_CV _181_ (
    .A(_100_),
    .B(_101_),
    .Y(_057_)
  );
  ANX1_CV _182_ (
    .A(_090_),
    .B(_097_),
    .Y(_102_)
  );
  ANX1_CV _183_ (
    .A(_057_),
    .B(_102_),
    .Y(_040_)
  );
  NDX1_CV _184_ (
    .A(_068_),
    .B(_098_),
    .Y(_103_)
  );
  ORX1_CV _185_ (
    .A(_068_),
    .B(_098_),
    .Y(_104_)
  );
  ANX1_CV _186_ (
    .A(_090_),
    .B(_104_),
    .Y(_105_)
  );
  ANX1_CV _187_ (
    .A(_103_),
    .B(_105_),
    .Y(_041_)
  );
  ENX1_CV _188_ (
    .A(_069_),
    .B(_068_),
    .Y(_106_)
  );
  NDX1_CV _189_ (
    .A(_059_),
    .B(_099_),
    .Y(_107_)
  );
  NDX1_CV _190_ (
    .A(_098_),
    .B(_106_),
    .Y(_108_)
  );
  NDX1_CV _191_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NRX1_CV _192_ (
    .A(_141_),
    .B(_109_),
    .Y(_042_)
  );
  NDX1_CV _193_ (
    .A(_091_),
    .B(_098_),
    .Y(_110_)
  );
  ORX1_CV _194_ (
    .A(_060_),
    .B(_110_),
    .Y(_111_)
  );
  NDX1_CV _195_ (
    .A(_060_),
    .B(_110_),
    .Y(_112_)
  );
  ANX1_CV _196_ (
    .A(_090_),
    .B(_112_),
    .Y(_113_)
  );
  ANX1_CV _197_ (
    .A(_111_),
    .B(_113_),
    .Y(_043_)
  );
  EOX1_CV _198_ (
    .A(_061_),
    .B(_111_),
    .Y(_114_)
  );
  ANX1_CV _199_ (
    .A(_090_),
    .B(_114_),
    .Y(_044_)
  );
  ENX1_CV _200_ (
    .A(_072_),
    .B(_093_),
    .Y(_115_)
  );
  NDX1_CV _201_ (
    .A(_098_),
    .B(_115_),
    .Y(_116_)
  );
  NDX1_CV _202_ (
    .A(_062_),
    .B(_099_),
    .Y(_117_)
  );
  ANX1_CV _203_ (
    .A(_090_),
    .B(_116_),
    .Y(_118_)
  );
  ANX1_CV _204_ (
    .A(_117_),
    .B(_118_),
    .Y(_045_)
  );
  NDX1_CV _205_ (
    .A(_072_),
    .B(_098_),
    .Y(_119_)
  );
  NDX1_CV _206_ (
    .A(_094_),
    .B(_098_),
    .Y(_120_)
  );
  NDX1_CV _207_ (
    .A(_063_),
    .B(_120_),
    .Y(_121_)
  );
  ORX1_CV _208_ (
    .A(_063_),
    .B(_120_),
    .Y(_122_)
  );
  ANX1_CV _209_ (
    .A(_090_),
    .B(_122_),
    .Y(_123_)
  );
  ANX1_CV _210_ (
    .A(_121_),
    .B(_123_),
    .Y(_046_)
  );
  ORX1_CV _211_ (
    .A(_064_),
    .B(_098_),
    .Y(_124_)
  );
  EOX1_CV _212_ (
    .A(_074_),
    .B(_095_),
    .Y(_125_)
  );
  NDX1_CV _213_ (
    .A(_076_),
    .B(_125_),
    .Y(_126_)
  );
  NDX1_CV _214_ (
    .A(_124_),
    .B(_126_),
    .Y(_127_)
  );
  ANX1_CV _215_ (
    .A(_090_),
    .B(_127_),
    .Y(_047_)
  );
  ORX1_CV _216_ (
    .A(_075_),
    .B(_099_),
    .Y(_128_)
  );
  NDX1_CV _217_ (
    .A(_096_),
    .B(_098_),
    .Y(_129_)
  );
  NDX1_CV _218_ (
    .A(_065_),
    .B(_129_),
    .Y(_130_)
  );
  ORX1_CV _219_ (
    .A(_065_),
    .B(_129_),
    .Y(_131_)
  );
  ANX1_CV _220_ (
    .A(_090_),
    .B(_130_),
    .Y(_132_)
  );
  ANX1_CV _221_ (
    .A(_131_),
    .B(_132_),
    .Y(_048_)
  );
  NDX1_CV _222_ (
    .A(_133_),
    .B(_099_),
    .Y(_077_)
  );
  NDX1_CV _223_ (
    .A(_103_),
    .B(_077_),
    .Y(_049_)
  );
  NDX1_CV _224_ (
    .A(_134_),
    .B(_099_),
    .Y(_078_)
  );
  NDX1_CV _225_ (
    .A(_069_),
    .B(_098_),
    .Y(_079_)
  );
  NDX1_CV _226_ (
    .A(_078_),
    .B(_079_),
    .Y(_050_)
  );
  NDX1_CV _227_ (
    .A(_135_),
    .B(_099_),
    .Y(_080_)
  );
  NDX1_CV _228_ (
    .A(_070_),
    .B(_098_),
    .Y(_081_)
  );
  NDX1_CV _229_ (
    .A(_080_),
    .B(_081_),
    .Y(_051_)
  );
  NDX1_CV _230_ (
    .A(_136_),
    .B(_099_),
    .Y(_082_)
  );
  NDX1_CV _231_ (
    .A(_071_),
    .B(_098_),
    .Y(_083_)
  );
  NDX1_CV _232_ (
    .A(_082_),
    .B(_083_),
    .Y(_052_)
  );
  NDX1_CV _233_ (
    .A(_137_),
    .B(_099_),
    .Y(_084_)
  );
  NDX1_CV _234_ (
    .A(_119_),
    .B(_084_),
    .Y(_053_)
  );
  NDX1_CV _235_ (
    .A(_138_),
    .B(_099_),
    .Y(_085_)
  );
  NDX1_CV _236_ (
    .A(_073_),
    .B(_098_),
    .Y(_086_)
  );
  NDX1_CV _237_ (
    .A(_085_),
    .B(_086_),
    .Y(_054_)
  );
  ORX1_CV _238_ (
    .A(_139_),
    .B(_098_),
    .Y(_087_)
  );
  ORX1_CV _239_ (
    .A(_074_),
    .B(_099_),
    .Y(_088_)
  );
  ANX1_CV _240_ (
    .A(_087_),
    .B(_088_),
    .Y(_055_)
  );
  ORX1_CV _241_ (
    .A(_140_),
    .B(_098_),
    .Y(_089_)
  );
  ANX1_CV _242_ (
    .A(_128_),
    .B(_089_),
    .Y(_056_)
  );
  (* src = "ADCHandler.v:34" *)
  DFSRQNX1_CV _243_ (
    .CK(_167_),
    .D(_003_),
    .Q(analog_ramp),
    .QN(_142_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _244_ (
    .CK(clk),
    .D(_002_[0]),
    .Q(out[0]),
    .QN(_143_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _245_ (
    .CK(clk),
    .D(_002_[1]),
    .Q(out[1]),
    .QN(_144_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _246_ (
    .CK(clk),
    .D(_002_[2]),
    .Q(out[2]),
    .QN(_145_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _247_ (
    .CK(clk),
    .D(_002_[3]),
    .Q(out[3]),
    .QN(_146_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _248_ (
    .CK(clk),
    .D(_002_[4]),
    .Q(out[4]),
    .QN(_147_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _249_ (
    .CK(clk),
    .D(_002_[5]),
    .Q(out[5]),
    .QN(_148_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _250_ (
    .CK(clk),
    .D(_002_[6]),
    .Q(out[6]),
    .QN(_149_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _251_ (
    .CK(clk),
    .D(_002_[7]),
    .Q(out[7]),
    .QN(_150_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _252_ (
    .CK(clk),
    .D(_001_[0]),
    .Q(digital_ramp[0]),
    .QN(_151_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _253_ (
    .CK(clk),
    .D(_001_[1]),
    .Q(digital_ramp[1]),
    .QN(_152_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _254_ (
    .CK(clk),
    .D(_001_[2]),
    .Q(digital_ramp[2]),
    .QN(_153_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _255_ (
    .CK(clk),
    .D(_001_[3]),
    .Q(digital_ramp[3]),
    .QN(_154_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _256_ (
    .CK(clk),
    .D(_001_[4]),
    .Q(digital_ramp[4]),
    .QN(_155_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _257_ (
    .CK(clk),
    .D(_001_[5]),
    .Q(digital_ramp[5]),
    .QN(_156_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _258_ (
    .CK(clk),
    .D(_001_[6]),
    .Q(digital_ramp[6]),
    .QN(_157_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _259_ (
    .CK(clk),
    .D(_001_[7]),
    .Q(digital_ramp[7]),
    .QN(_158_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "ADCHandler.v:13" *)
  DFSRQNX1_CV _260_ (
    .CK(clk),
    .D(_000_),
    .Q(analog_ramp),
    .QN(_159_),
    .R(1'h0),
    .S(1'h0)
  );
  assign ADC_finished = 1'h0;
  assign _015_ = _152_;
  assign _018_ = _153_;
  assign _021_ = _154_;
  assign _025_ = _155_;
  assign _028_ = _156_;
  assign _032_ = _157_;
  assign _036_ = _158_;
  assign _073_ = digital_ramp[5];
  assign _072_ = digital_ramp[4];
  assign _071_ = digital_ramp[3];
  assign _070_ = digital_ramp[2];
  assign _069_ = digital_ramp[1];
  assign _068_ = digital_ramp[0];
  assign _076_ = enable;
  assign _067_ = clk;
  assign _058_ = analog_ramp;
  assign _003_ = _057_;
  assign _141_ = reset;
  assign _000_ = _040_;
  assign _001_[0] = _041_;
  assign _059_ = _152_;
  assign _001_[1] = _042_;
  assign _060_ = _153_;
  assign _001_[2] = _043_;
  assign _061_ = _154_;
  assign _001_[3] = _044_;
  assign _062_ = _155_;
  assign _001_[4] = _045_;
  assign _063_ = _156_;
  assign _001_[5] = _046_;
  assign _074_ = digital_ramp[6];
  assign _064_ = _157_;
  assign _001_[6] = _047_;
  assign _075_ = digital_ramp[7];
  assign _065_ = _158_;
  assign _001_[7] = _048_;
  assign _133_ = out[0];
  assign _002_[0] = _049_;
  assign _134_ = out[1];
  assign _002_[1] = _050_;
  assign _135_ = out[2];
  assign _002_[2] = _051_;
  assign _136_ = out[3];
  assign _002_[3] = _052_;
  assign _137_ = out[4];
  assign _002_[4] = _053_;
  assign _138_ = out[5];
  assign _002_[5] = _054_;
  assign _139_ = out[6];
  assign _002_[6] = _055_;
  assign _140_ = out[7];
  assign _002_[7] = _056_;
  assign _167_ = _066_;
endmodule
